### ISSUE TITLE
feat: error handling in can_unpack thread

### ISSUE THREAD

**Issue by rureverek** [sufst/on-car-telemetry#18]
### Description
Implement error handling in can_unpack thread. This might be implemented by putting the device into an infinite loop and setting the on-board LED. Different error codes might be distinguished by different periods/scheme of LED blinking.

**Comment by rureverek** [comment]
@t-bre I have two ideas how this can be implemented: 
1. Create separate thread that is handling errors. It waits until detect the error code defined as a variable in thread's context struct. For example: In unpack thread it would be `error_code` variable in `unpack_context_t` struct. Depending on error code it start some scheme of LED blinking. The advantage there's only one error handling function easy to be appended with new error codes from different threads.
2. Create function inside thread. For example: In unpack thread it would be `void error_handling()` which is infinite loop with certain LED function. Simpler, but each thread will have different error_handling function. Also, if error happen during initialisation, it will block further program execution.

**Comment by t-bre** [comment]
In case it helps, we had something similar to option 1 last year for the VCU. There was an "error thread" which was suspended on a semaphore. There was an error registering function which would increment the semaphore, elevate the error thread priority to zero and suspend the current thread. This thread would then shutdown the VCU to a safe state and blink the red LED. However, the scenario here is somewhat different since the system is "non-critical" - it has no influence on the tractive system, it's effectively an "observer" of the car's CAN bus. 

The error handling system is really up to you, I'm not sure I have any particular ideas for it. I have a few suggestions in general regarding errors in this system though:

- For non-critical errors (e.g. a queue is full), it would be good to try and recover (e.g. by flushing the queue, or discarding the message being posted to the queue).
- For critical errors which we don't think can easily be resolved, it might be good to actually do a soft reset of the entire system. This is something we would definitely want at competition, so if there is an issue with the telemetry it can try to restart itself.
- We might want a separate behaviour for debugging purposes, especially if we have a soft reset feature which could potentially cause an infinite cycle of resets if there is a bug in the code causing a critical error.
- Some errors might be valid to ignore, however it will be important to clean up properly in such a case (e.g. freeing RTCAN message).

**Comment by rureverek** [comment]
@t-bre Just created a PR here. Could you take a look? I didn't implement any recover behaviours yet and critical_error handling is quite limited so far.
